### ISSUE TITLE
Speed seems to be too high

### ISSUE THREAD

**Issue by sivizius** [cruvolo/ramspeed-smp#1]
Thank you for this tool, it was easy to build, run and understand.
But it seems to me, that the result is too good for the RAM that is actually installed. I have some DDR3-1600 RAM (checked with dmidecode and by label), where I expected to have results in the range of 12–13 GB/s but I achieved 14 GB/s (INTmem and FLOATmem), 15 GB/s (MMXmem and SSEmem) and 18–20 GB/s (MMXmem (nt) and SSEmem (nt)) with your tool. Even the lowest result is somewhat too fast.
Any ideas? Or do I have better memory than think I have?

**Comment by sivizius** [comment]
Turns out: I have two DDR3-1600-modules and if two consecutive IO-operations happen on different modules, I actually have twice the speed. Assuming the probability of two consecutive IOs on the same/different module is 50%, I would expect an average bandwidth of 1.5·12.8 GB/s which is 19.2 GB/s. Due to caching (Cache-Size is 6 MB) sometimes IO-operations are not on the RAM but on the Cache, which is significantly faster. Therefore my results with 20 GB/s with SSEmen (nt) are actually correct.

**Comment by cruvolo** [comment]
Hi.  I'm not the original author. I only updated the code for current compilers and assemblers.  Please see here: http://www.alasir.com/software/ramspeed/ and note that two systems with DDR3-1333 give very different results.  The memory access and timing is highly dependent on system settings and architecture, can yield different bandwidths depending.  Hope this helps.
